# packages/components/extractors/pyproject.toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pipeline-extractors"
description = "Компоненты для извлечения данных в pipeline фреймворке"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [
    { name = "Pipeline Framework Team", email = "team@example.com" },
]
keywords = ["pipeline", "etl", "data-extraction", "extractors"]
requires-python = ">=3.11"

# Базовые зависимости
dependencies = [
    "pipeline-core",  # Локальная зависимость из workspace
    "pandas>=2.0.0",
]

dynamic = ["version"]

[project.optional-dependencies]
# Файловые экстракторы
files = [
    "aiofiles>=23.0.0",
    "aiocsv>=1.3.0",
]

# Расширенные форматы
formats = [
    "polars>=0.20.0",
    "openpyxl>=3.1.0",
    "pyarrow>=14.0.0",
]

# API экстракторы
api = [
    "httpx>=0.25.0",
    "requests>=2.31.0",
]

# Development
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "ruff>=0.6.0",
    "pyright>=1.1.380",
]

[tool.hatch.version]
path = "src/pipeline_extractors/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/pipeline_extractors"]

[tool.uv.sources]
pipeline-core = { workspace = true }