[project]
name = "extractor-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ryibalchenko.NV", email = "Ryibalchenko.NV@dns-shop.ru" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
extractor-sql = "extractor_sql:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
